version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "3001:3001"
    networks:
      - eventmap-network
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=eventmap
      - DB_PASSWORD=eventmap
      - DB_NAME=eventmap
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run migrate && npm run seed && npm start"

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: 'eventmap'
      POSTGRES_USER: 'eventmap'
      POSTGRES_PASSWORD: 'eventmap'
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgres
    networks:
      - eventmap-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "eventmap", "-d", "eventmap"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  eventmap-network:
    driver: bridge