version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=eventmap
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'eventmap'
      MYSQL_ROOT_PASSWORD: 'yourpassword'
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s